In [3]:
!pip install sympy

  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)

   ---------------------------------------- 0/2 [mpmath]
   ---------------------------------------- 0/2 [mpmath]
   ---------------------------------------- 0/2 [mpmath]
   ---------------------------------------- 0/2 [mpmath]
   ---------------------------------------- 0/2 [mpmath]
   ---------------------------------------- 0/2 [mpmath]
   ---------------------------------------- 0/2 [mpmath]
   ---------------------------------------- 0/2 [mpmath]
   ---------------------------------------- 0/2 [mpmath]
   ---------------------------------------- 0/2 [mpmath]
   ---------------------------------------- 0/2 [mpmath]
   -------------------- ------------------- 1/2 [sympy]
   -------------------- ------------------- 1/2 [sympy]
   -------------------- -------


[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import sympy as sp
# (a) f(x) = (x**2+2)**3
x = sp.Symbol('x')
fx = (x**2+2)**3
sp.diff(fx,x)

6*x*(x**2 + 2)**2

In [5]:
x = sp.Symbol('x')
gx = 1/(x**4+1)**2
sp.diff(gx,x)

-8*x**3/(x**4 + 1)**3

In [6]:
x  = sp.Symbol('x')
gx  = 3*sp.log(x,2) - x*sp.log(x)
print("g'(x) = ", sp.simplify(sp.diff(gx,x)))

g'(x) =  -log(x) - 1 + 3/(x*log(2))


In [1]:
print(type(2**30))

<class 'int'>


In [2]:
import numpy as np

# Zero vector
zero_vec = np.zeros(3)
# One vector
one_vec = np.ones(3)
# Square matrix
square_mat = np.array([[1, 2], [3, 4]])
# Diagonal matrix
diag_mat = np.diag([1, 2, 3])
# Identity matrix
identity_mat = np.eye(3)
# Symmetric matrix
sym_mat = np.array([[1, 2], [2, 3]])

In [3]:
print("Zero Vector:\n", zero_vec)
print("One Vector:\n", one_vec)
print("Square Matrix:\n", square_mat)
print("Diagonal Matrix:\n", diag_mat)
print("Identity Matrix:\n", identity_mat)
print("Symmetric Matrix:\n", sym_mat)

Zero Vector:
 [0. 0. 0.]
One Vector:
 [1. 1. 1.]
Square Matrix:
 [[1 2]
 [3 4]]
Diagonal Matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Symmetric Matrix:
 [[1 2]
 [2 3]]


In [5]:
import numpy as np

# Price vector (in won)
p = np.array([1_000_000, 800_000, 500_000])
# Quantity vector
n = np.array([3, 4, 5])
print("Price vector (p):", p)
print("Quantity vector (n):", n)

Price vector (p): [1000000  800000  500000]
Quantity vector (n): [3 4 5]


In [6]:
total = np.dot(p, n)
print("Total amount required:", total)

Total amount required: 8700000


In [7]:
from sklearn.datasets import load_digits
X = load_digits().data

In [8]:
similarity = np.dot(X[0], X[9])
print("Similarity:", similarity)

Similarity: 2807.0


In [10]:
similarity_matrix = np.dot(X, X.T)
print("Similarity matrix shape:", similarity_matrix.shape)

Similarity matrix shape: (1797, 1797)


In [12]:
similarity_matrix = np.dot(X, X.T)
print("Similarity matrix shape:", similarity_matrix.shape)

Similarity matrix shape: (1797, 1797)


In [13]:
A = np.array([[2, 0], [0, 1]])
A_inv = np.linalg.inv(A)
print(A_inv)

[[0.5 0. ]
 [0.  1. ]]


In [3]:
import pandas as pd
import numpy as np
boston = pd.read_csv('C:\\Users\\shash\\OneDrive\\Desktop\\SamsungInnovationCampus-AI-ML\\SamsungInnovationCampus-AI-ML\\DataSets\\data_boston.csv')
X = boston.drop('PRICE', axis=1)
y = boston['PRICE']
w = np.linalg.lstsq(X, y, rcond=None)[0]
print(w)

[-9.16297843e-02  4.86751203e-02 -3.77930006e-03  2.85636751e+00
 -2.88077933e+00  5.92521432e+00 -7.22447929e-03 -9.67995240e-01
  1.70443393e-01 -9.38925373e-03 -3.92425680e-01  1.49832102e-02
 -4.16972624e-01]


In [17]:
import numpy as np

a = np.array([5, 3, 4, 4])
b = np.array([3, 1, 2, 3])
c = np.array([4, 3, 4, 3])

def euclidean(u, v):
    return np.linalg.norm(u - v)

print("a-b:", euclidean(a, b))
print("a-c:", euclidean(a, c))
print("b-c:", euclidean(b, c))

a-b: 3.605551275463989
a-c: 1.4142135623730951
b-c: 3.0


In [18]:
from numpy import dot
from numpy.linalg import norm

def cosine(u, v):
    return 1 - dot(u, v) / (norm(u) * norm(v))

print("a-b:", cosine(a, b))
print("a-c:", cosine(a, c))
print("b-c:", cosine(b, c))

a-b: 0.024678695555243824
a-c: 0.007757361052522449
b-c: 0.056371480608658375


In [19]:
D = np.array([[2, 1], [1, 2]])
eigvals = np.linalg.eigvals(D)
print(eigvals)

[3. 1.]


In [21]:
import sympy as sp

x, y, k, a, b = sp.symbols('x y k a b')

# (a)
f1 = x**3 - 1
df1 = sp.diff(f1, x)
print("f'(x) =", df1)


f'(x) = 3*x**2


In [24]:
# (b)
f2 = sp.log(x**2 - 3*k)
df2 = sp.diff(f2, x)
print("f'(x) =", df2)

f'(x) = 2*x/(-3*k + x**2)


In [25]:
f3 = sp.exp(a*x**b)
df3 = sp.diff(f3, x)
print("f'(x) =", df3)

f'(x) = a*b*x**b*exp(a*x**b)/x


In [26]:
# (d) Partial derivatives
f4 = sp.exp(x**2 + 2*y**2)
fx = sp.diff(f4, x)
fy = sp.diff(f4, y)
fxx = sp.diff(fx, x)
fxy = sp.diff(fx, y)
fyx = sp.diff(fy, x)
fyy = sp.diff(fy, y)
print("f_x =", fx)
print("f_y =", fy)
print("f_xx =", fxx)
print("f_xy =", fxy)
print("f_yx =", fyx)
print("f_yy =", fyy)

f_x = 2*x*exp(x**2 + 2*y**2)
f_y = 4*y*exp(x**2 + 2*y**2)
f_xx = 4*x**2*exp(x**2 + 2*y**2) + 2*exp(x**2 + 2*y**2)
f_xy = 8*x*y*exp(x**2 + 2*y**2)
f_yx = 8*x*y*exp(x**2 + 2*y**2)
f_yy = 16*y**2*exp(x**2 + 2*y**2) + 4*exp(x**2 + 2*y**2)


### Boston House Price Problem: Linear Prediction Model (Ax = b) with 4 Features and 4 Data Points


In [6]:
import pandas as pd
import numpy as np
boston = pd.read_csv('C:\\Users\\shash\\OneDrive\\Desktop\\SamsungInnovationCampus-AI-ML\\SamsungInnovationCampus-AI-ML\\DataSets\\data_boston.csv')
A = boston.iloc[:4][['CRIM', 'NOX', 'RM', 'AGE']].values
b = boston.iloc[:4]['PRICE'].values
x = np.linalg.lstsq(A, b, rcond=None)[0]
print('Weight vector x:', x)

Weight vector x: [-3.12710043e+02 -1.15193942e+02  1.44996465e+01 -1.13259317e-01]


#### Interpretation of the weight vector x for CRIM, NOX, RM, AGE
- Positive weights: factors that increase house price.
- Negative weights: factors that decrease house price.
- Example: If CRIM weight is negative, house price is in inverse proportion to crime rate (CRIM).

### Boston House Price Problem: Least Squares Solution with All Features and Data


In [7]:
X = boston.drop('PRICE', axis=1).values
y = boston['PRICE'].values
w = np.linalg.lstsq(X, y, rcond=None)[0]
print('Weight vector w:', w)

Weight vector w: [-9.16297843e-02  4.86751203e-02 -3.77930006e-03  2.85636751e+00
 -2.88077933e+00  5.92521432e+00 -7.22447929e-03 -9.67995240e-01
  1.70443393e-01 -9.38925373e-03 -3.92425680e-01  1.49832102e-02
 -4.16972624e-01]


#### Interpretation of the weight vector w for all features
- Positive weights: factors that increase house price.
- Negative weights: factors that decrease house price.
- Example: If CRIM weight is negative, house price is in inverse proportion to crime rate (CRIM).


#### Difference between the two results
The full least-squares solution uses all data and features, so weights are more accurate and reflect all factors, unlike the simplified 4-row/4-feature version.