In [2]:
import pandas as pd

messages = pd.read_csv(
    r'C:\Users\shash\Desktop\SamsungInnovationCampus-AI-ML\SamsungInnovationCampus-AI-ML\DataSets\spam.csv',
    encoding='latin-1'
)
messages = messages[['v1','v2']]
messages.columns = ['label','message']

In [3]:
messages

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will Ì_ b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [4]:
## Data Cleaning And Preprocessing
import re #For regular expression operations
import nltk
nltk.download('stopwords') #For downloading the stop words from the nltk library

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\shash\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [5]:
from nltk.corpus import stopwords #For stop words which are commonly used words in a language that do not add much meaning to a sentence and can be removed without losing the context of the sentence
from nltk.stem.porter import PorterStemmer #For stemming which is the process of reducing a word to its root form. For example, the words "running", "runner", and "ran" can be reduced to the root word "run". This helps in reducing the dimensionality of the data and improving the performance of machine learning models.
ps=PorterStemmer()

In [6]:
corpus=[] #Creating an empty list to store the cleaned reviews
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i]) #Substituting all the characters other than a-z and A-Z with space
    review=review.lower() #Converting all the characters to lower case
    review=review.split() #Splitting the review into list of words
    #Stemming and removing stop words from the review and then joining the words back to form a cleaned review and appending it to the corpus list
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [7]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

## Create Bag Of Words

In [8]:
## Create the Bag OF Words model
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True

"""Counter Vectorizer is a class in the sklearn library that is used to convert a collection of text documents to a matrix of token counts. 
It creates a bag of words model where each row represents a document and each column represents a word in the vocabulary. 
The value in each cell represents the count of the word in the document. By setting binary=True, we can create a binary bag of words model 
where the value in each cell is 1 if the word is present in the document and 0 if it is not present. 
This can help in reducing the dimensionality of the data and improving the performance of machine learning models."""


cv=CountVectorizer(max_features=100,binary=True) #Creating a CountVectorizer object with a maximum of 100 features and binary=True to create a binary bag of words model
X=cv.fit_transform(corpus).toarray() #Fitting the CountVectorizer object to the corpus and transforming it into a sparse matrix and then converting it to an array

In [9]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.3g" % x))
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0

### N-Grams

In [10]:
cv.vocabulary_

{'go': np.int64(22),
 'great': np.int64(25),
 'got': np.int64(24),
 'wat': np.int64(90),
 'ok': np.int64(56),
 'free': np.int64(18),
 'win': np.int64(94),
 'text': np.int64(77),
 'txt': np.int64(85),
 'say': np.int64(67),
 'alreadi': np.int64(0),
 'think': np.int64(80),
 'hey': np.int64(28),
 'week': np.int64(92),
 'back': np.int64(3),
 'like': np.int64(38),
 'still': np.int64(73),
 'send': np.int64(69),
 'even': np.int64(15),
 'friend': np.int64(19),
 'prize': np.int64(62),
 'claim': np.int64(7),
 'call': np.int64(4),
 'mobil': np.int64(47),
 'co': np.int64(8),
 'home': np.int64(30),
 'want': np.int64(89),
 'today': np.int64(82),
 'cash': np.int64(6),
 'day': np.int64(12),
 'repli': np.int64(64),
 'www': np.int64(96),
 'right': np.int64(65),
 'thank': np.int64(78),
 'take': np.int64(75),
 'time': np.int64(81),
 'use': np.int64(87),
 'messag': np.int64(44),
 'oh': np.int64(55),
 'ye': np.int64(97),
 'make': np.int64(42),
 'way': np.int64(91),
 'feel': np.int64(16),
 'dont': np.int64(14

##### Ngram is a contiguous sequence of n items from a given sample of text or speech. The items can be phonemes, syllables, letters, words or base pairs according to the application. The n-grams typically are collected from a text or speech corpus. When the items are words, n-grams may also be called shingles. 
###### Unigram is a contiguous sequence of 1 item
###### Digram is a contiguous sequence of 2 items
###### Trigram is a contiguous sequence of 3 items

In [11]:
## Create the Bag OF Words model with ngram
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
"""CounterVectorizer(ngram_range=(2,3)) will create a bag of words model with ngrams of size 2 and 3. 
For example, if the review is "I love this movie", then the bigrams will be "I love", "love this", "this movie" and 
the trigrams will be "I love this", "love this movie".
This will help in capturing the context of the words in the review and improving the performance of machine learning models."""

cv=CountVectorizer(max_features=500,binary=True,ngram_range=(2,3)) #Creating a CountVectorizer object with a maximum of 100 features, binary=True to create a binary bag of words model and ngram_range=(2,3) to create a bag of words model with ngrams of size 2 and 3
X=cv.fit_transform(corpus).toarray()

In [12]:
cv.vocabulary_

{'free entri': np.int64(139),
 'rate appli': np.int64(338),
 'claim call': np.int64(66),
 'call claim': np.int64(27),
 'claim code': np.int64(67),
 'call claim code': np.int64(28),
 'updat latest': np.int64(443),
 'latest colour': np.int64(220),
 'free call': np.int64(136),
 'call mobil': np.int64(39),
 'entitl updat latest': np.int64(125),
 'chanc win': np.int64(64),
 'win cash': np.int64(486),
 'repli hl': np.int64(347),
 'chanc win cash': np.int64(65),
 'repli hl info': np.int64(348),
 'txt word': np.int64(436),
 'dont miss': np.int64(114),
 'let know': np.int64(223),
 'feel like': np.int64(132),
 'repli ye': np.int64(350),
 'go home': np.int64(158),
 'anyth lor': np.int64(5),
 'call repli': np.int64(45),
 'mobil free': np.int64(266),
 'free camcord': np.int64(137),
 'pleas call': np.int64(317),
 'deliveri tomorrow': np.int64(110),
 'lt gt': np.int64(239),
 'miss call': np.int64(262),
 'want go': np.int64(474),
 'first time': np.int64(135),
 'like lt': np.int64(226),
 'like lt gt': 

In [13]:
X
#The shape of the matrix is (5572, 500) which means there are 5572 reviews and 500 features in the bag of words model.

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [14]:
X.shape

(5572, 500)

In [15]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet') #For downloading the wordnet from the nltk library
wordlematizer=WordNetLemmatizer() #Creating a WordNetLemmatizer object

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\shash\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [16]:
corpus=[] #Creating an empty list to store the cleaned reviews
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i]) #Substituting all the characters other than a-z and A-Z with space
    review=review.lower() #Converting all the characters to lower case
    review=review.split() #Splitting the review into list of words
    #Lemmatizing and removing stop words from the review and then joining the words back to form a cleaned review and appending it to the corpus list
    review=[wordlematizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [17]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw'

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
"""TfidfVectorizer is a class in the sklearn library that is used to convert a collection of text documents to a matrix of TF-IDF features."""

'TfidfVectorizer is a class in the sklearn library that is used to convert a collection of text documents to a matrix of TF-IDF features.'

In [19]:
tfidf = TfidfVectorizer(max_features=500) #Creating a TfidfVectorizer object with a maximum of 500 features
X = tfidf.fit_transform(corpus).toarray() #Fitting the TfidfVectorizer object to the corpus and transforming it into a sparse matrix and then converting it to an array

In [20]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.3g" % x))

In [21]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.48, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0.66, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.285, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0.244, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.37, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.476, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0

In [22]:
tfidf = TfidfVectorizer(max_features= 100, ngram_range=(2, 3)) #Creating a TfidfVectorizer object with a maximum of 500 features and considering unigrams and bigrams
X = tfidf.fit_transform(corpus).toarray() #Fitting the TfidfVectorizer object to the corpus and transforming it into a sparse matrix and then converting it to an array

In [23]:
tfidf.vocabulary_

{'free entry': np.int64(32),
 'claim call': np.int64(17),
 'call claim': np.int64(3),
 'free call': np.int64(31),
 'chance win': np.int64(16),
 'txt word': np.int64(90),
 'let know': np.int64(52),
 'please call': np.int64(67),
 'lt gt': np.int64(58),
 'want go': np.int64(97),
 'like lt': np.int64(53),
 'like lt gt': np.int64(54),
 'sorry call': np.int64(82),
 'call later': np.int64(11),
 'sorry call later': np.int64(83),
 'ur awarded': np.int64(91),
 'hi hi': np.int64(44),
 'call customer': np.int64(4),
 'customer service': np.int64(23),
 'cash prize': np.int64(15),
 'call customer service': np.int64(5),
 'trying contact': np.int64(88),
 'draw show': np.int64(28),
 'show prize': np.int64(80),
 'prize guaranteed': np.int64(74),
 'guaranteed call': np.int64(40),
 'valid hr': np.int64(95),
 'draw show prize': np.int64(29),
 'show prize guaranteed': np.int64(81),
 'prize guaranteed call': np.int64(75),
 'selected receive': np.int64(77),
 'private account': np.int64(71),
 'account statement

In [24]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

### Word2Vec
#### Average Word2Vec is a technique used in natural language processing to represent a document as a vector by averaging the word vectors of the individual words in the document.

In [25]:
!pip install gensim


[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [26]:
import gensim
from gensim.models import Word2Vec, KeyedVectors 
##Word2Vec is a class in the gensim library that is used to create word embeddings.
##KeyedVectors is a class in the gensim library that is used to load pre-trained word embeddings and perform various operations on them such as finding similar words, calculating cosine similarity, etc.

In [27]:
import gensim.downloader as api
model = api.load("word2vec-google-news-300")

In [28]:
vec_king = model['king'] #Getting the word vector for the word 'king'
vec_king

array([0.126, 0.0298, 0.00861, 0.14, -0.0256, -0.0361, 0.112, -0.198, 0.0513, 0.363, -0.242, -0.303, -0.178, -0.0249, -0.168, -0.17, 0.0347, 0.00522, 0.0464, 0.129, 0.137, 0.113, 0.0596, 0.137, 0.101, -0.177, -0.252, 0.0598, 0.342, -0.0311, 0.104, 0.0618, 0.125, 0.4, -0.322, 0.084, 0.0391, 0.00586, 0.0703, 0.173, 0.139, -0.231, 0.283, 0.143, 0.342, -0.0239, -0.11, 0.0332, -0.0547, 0.0153, -0.162, 0.158, -0.26, 0.0201, -0.163, 0.00136, -0.145, -0.0569, 0.043, -0.0247, 0.186, 0.447, 0.00958, 0.132, 0.0986, -0.186, -0.1, -0.134, -0.125, 0.283, 0.123, 0.0532, -0.178, 0.0859, -0.0219, 0.0205, -0.14, 0.0251, 0.139, -0.105, 0.139, 0.0889, -0.0752, -0.0214, 0.173, 0.0464, -0.266, 0.00891, 0.149, 0.0378, 0.238, -0.125, -0.218, -0.182, 0.0298, 0.0571, -0.0289, 0.0125, 0.0967, -0.231, 0.0581, 0.0669, 0.0708, -0.309, -0.215, 0.146, -0.428, -0.0094, 0.154, -0.0767, 0.289, 0.277, -0.000486, -0.137, 0.324, -0.246, -0.00304, -0.212, 0.125, 0.27, 0.204, 0.0825, -0.201, -0.16, -0.0378, -0.12, 0.115, -0.

In [29]:
model['Cricket']

array([-0.381, -0.145, 0.303, -0.212, -0.175, 0.0425, 0.254, -0.204, -0.0894, 0.0276, 0.0981, -0.271, -0.0162, 0.169, 0.256, 0.0271, 0.0698, 0.135, 0.0781, 0.195, -8.54e-05, -0.0317, 0.0713, -0.5, 0.379, 0.137, 0.0483, 0.512, 0.652, -0.194, -0.201, 0.0972, -0.355, 0.0128, 0.0481, 0.0757, -0.291, -0.0325, 0.021, -0.124, 0.0192, -0.0527, 0.227, 0.102, -0.0815, -0.312, 0.146, -0.324, 0.0422, 0.191, -0.164, 0.196, 0.227, 0.00226, 0.293, -0.412, -0.249, -0.436, -0.16, -0.248, -0.281, -0.0417, -0.354, 0.287, 0.0181, 0.0197, -0.244, 0.0205, 0.354, -0.0708, 0.215, -0.0776, -0.221, -0.15, -0.129, -0.227, 0.14, -0.254, 0.484, -0.35, -0.256, 0.268, -0.109, 0.23, -0.153, -0.0791, -0.0903, 0.173, -0.32, 0.118, 0.0947, -0.061, -0.00461, -0.177, -0.0894, 0.219, 0.338, -0.0684, 0.0532, -0.008, -0.104, 0.0452, 0.0791, -0.0972, 0.252, -0.0352, 0.326, -0.129, -0.0874, -0.0566, -0.00479, 0.171, 0.233, -0.227, 0.473, 0.264, -0.0598, -0.0645, 0.334, 0.0532, -0.0342, 0.0322, -0.0972, -0.03, -0.346, 0.432, -0

In [30]:
model.most_similar('cricket') #Finding the most similar words to the word 'cricket' in the word embedding model

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [31]:
model.most_similar('king') #Finding the most similar words to the word 'king' in the word embedding model

[('kings', 0.7138045430183411),
 ('queen', 0.6510956883430481),
 ('monarch', 0.6413194537162781),
 ('crown_prince', 0.6204220056533813),
 ('prince', 0.6159993410110474),
 ('sultan', 0.5864824056625366),
 ('ruler', 0.5797567367553711),
 ('princes', 0.5646552443504333),
 ('Prince_Paras', 0.5432944297790527),
 ('throne', 0.5422105193138123)]

In [32]:
model.similarity('king', 'queen') #Calculating the cosine similarity between the word vectors of 'king' and 'queen' in the word embedding model

np.float32(0.6510957)

In [ ]:
model.similarity("hockey", "sports") #Calculating the cosine similarity between the word vectors of 'hockey' and 'sports' in the word embedding model

np.float32(0.53541523)

In [34]:
model.most_similar('excited') #Finding the most similar words to the word 'excited' in the pre-trained word embeddings model

[('thrilled', 0.8411031365394592),
 ('enthused', 0.7252784371376038),
 ('pleased', 0.7137202024459839),
 ('delighted', 0.7036551237106323),
 ('proud', 0.6833416223526001),
 ('ecstatic', 0.675162136554718),
 ('psyched', 0.6678282618522644),
 ('exciting', 0.6454532146453857),
 ('elated', 0.6269152164459229),
 ('happy', 0.6247665882110596)]

In [35]:
vec = model['king'] - model['man'] + model['woman'] #Performing the word analogy task of "king" is to

In [36]:
vec

array([0.043, -0.178, -0.129, 0.115, 0.00269, -0.102, 0.196, -0.18, 0.0195, 0.41, -0.368, -0.396, -0.157, 0.00146, -0.093, -0.116, -0.0552, -0.108, 0.0791, 0.199, 0.239, 0.0634, -0.0217, 0, 0.0472, -0.218, -0.345, 0.0637, 0.316, -0.198, 0.0859, -0.0812, -0.0371, 0.316, -0.342, -0.0469, 0.0977, 0.084, -0.0972, 0.0518, -0.05, -0.221, 0.229, 0.126, 0.249, 0.021, -0.11, 0.0581, -0.0336, 0.13, 0.0242, 0.0348, -0.26, 0.242, -0.322, 0.0145, -0.159, -0.0837, 0.165, 0.00159, 0.31, 0.316, 0.00739, 0.241, 0.0491, -0.0986, 0.0291, 0.149, -0.0483, 0.236, 0.221, 0.125, -0.139, 0.154, 0.0719, 0.13, -0.106, 0.0601, 0.315, 0.11, 0.085, 0.0771, -0.0217, 0.0612, -0.19, 0.208, -0.163, 0.114, 0.201, 0.0607, 0.128, -0.311, -0.28, -0.156, 0.0415, 0.0988, 0.17, -0.0349, 0.208, -0.099, 0.00439, -0.0728, -0.0425, -0.409, -0.276, 0.164, -0.558, -0.202, 0.212, -0.0981, 0.231, 0.276, 0.168, -0.045, 0.172, -0.377, -0.00352, -0.302, 0.174, 0.33, 0.201, 0.118, -0.138, -0.107, 0.0862, 0.106, 0.145, 0.00305, 0.0181, 0.

In [37]:
model.most_similar([vec]) #Finding the most similar words to the word 'vec' in the pre-trained word embeddings model

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]