In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sentence = ['I love my country',
            'I am a good boy',
            'I am a good developer',
            'I am a awesome person',
            'I am a best friend']

In [3]:
sentence

['I love my country',
 'I am a good boy',
 'I am a good developer',
 'I am a awesome person',
 'I am a best friend']

In [4]:
##Define the vocabulary size
vocab_size = 5000

In [6]:
##One hot representation
one_hot_representations = [one_hot(words, vocab_size) for words in sentence]
one_hot_representations
##This is gives the output as a list of list. Each word is represented as a number. This number is the index of the word in the vocabulary. The vocabulary is created by the one_hot function. The one_hot function takes the sentence and the vocabulary size as input and returns the one hot representation of the sentence.

[[3094, 2385, 1571, 3312],
 [3094, 980, 1057, 1644, 3036],
 [3094, 980, 1057, 1644, 3277],
 [3094, 980, 1057, 1510, 107],
 [3094, 980, 1057, 2501, 4603]]

In [7]:
##word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences #To make all the sentences of the same length
from tensorflow.keras.models import Sequential #To create a sequential model

In [8]:
import numpy as np

In [9]:
sentence_length = 8
embedded_docs = pad_sequences(one_hot_representations, padding='pre', maxlen=sentence_length)
embedded_docs

array([[   0,    0,    0,    0, 3094, 2385, 1571, 3312],
       [   0,    0,    0, 3094,  980, 1057, 1644, 3036],
       [   0,    0,    0, 3094,  980, 1057, 1644, 3277],
       [   0,    0,    0, 3094,  980, 1057, 1510,  107],
       [   0,    0,    0, 3094,  980, 1057, 2501, 4603]])

In [10]:
##Feature representation
dimension = 10
model = Sequential()
model.add(Embedding(vocab_size, dimension, input_length=sentence_length))
model.compile('adam', 'mse') ##To compile the model we need to specify the optimizer and the loss function. Here we are using 'adam' as the optimizer and 'mse' as the loss function. The 'adam' optimizer is a popular optimization algorithm that is used in deep learning. The 'mse' loss function is used for regression problems. It stands for mean squared error. It calculates the average of the squares of the errors between the predicted values and the actual values.

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             50000     
                                                                 
Total params: 50000 (195.31 KB)
Trainable params: 50000 (195.31 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 96ms/step


array([[[-0.02392325,  0.01780721, -0.02010065,  0.0206948 ,
         -0.03163216,  0.02880162,  0.04817691, -0.02968141,
         -0.01473711, -0.03221624],
        [-0.02392325,  0.01780721, -0.02010065,  0.0206948 ,
         -0.03163216,  0.02880162,  0.04817691, -0.02968141,
         -0.01473711, -0.03221624],
        [-0.02392325,  0.01780721, -0.02010065,  0.0206948 ,
         -0.03163216,  0.02880162,  0.04817691, -0.02968141,
         -0.01473711, -0.03221624],
        [-0.02392325,  0.01780721, -0.02010065,  0.0206948 ,
         -0.03163216,  0.02880162,  0.04817691, -0.02968141,
         -0.01473711, -0.03221624],
        [-0.04065194, -0.03123769,  0.00329596,  0.0239308 ,
         -0.03790893,  0.0350965 , -0.03138222,  0.03958652,
         -0.00717187,  0.01186094],
        [-0.02288429, -0.02818208, -0.02962834, -0.0435917 ,
          0.04523957, -0.02007269, -0.02853524, -0.00467714,
          0.02959627, -0.0364623 ],
        [ 0.04683305, -0.02150548, -0.02945917,  0.0

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 3094, 2385, 1571, 3312])

In [14]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 48ms/step


array([[-0.02392325,  0.01780721, -0.02010065,  0.0206948 , -0.03163216,
         0.02880162,  0.04817691, -0.02968141, -0.01473711, -0.03221624],
       [-0.02392325,  0.01780721, -0.02010065,  0.0206948 , -0.03163216,
         0.02880162,  0.04817691, -0.02968141, -0.01473711, -0.03221624],
       [-0.02392325,  0.01780721, -0.02010065,  0.0206948 , -0.03163216,
         0.02880162,  0.04817691, -0.02968141, -0.01473711, -0.03221624],
       [-0.02392325,  0.01780721, -0.02010065,  0.0206948 , -0.03163216,
         0.02880162,  0.04817691, -0.02968141, -0.01473711, -0.03221624],
       [-0.04065194, -0.03123769,  0.00329596,  0.0239308 , -0.03790893,
         0.0350965 , -0.03138222,  0.03958652, -0.00717187,  0.01186094],
       [-0.02288429, -0.02818208, -0.02962834, -0.0435917 ,  0.04523957,
        -0.02007269, -0.02853524, -0.00467714,  0.02959627, -0.0364623 ],
       [ 0.04683305, -0.02150548, -0.02945917,  0.03408575,  0.0474048 ,
         0.03685052, -0.03505235, -0.03982376