In [1]:
import numpy as np

In [2]:
import numpy as np

b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Delete column at index 1 (i.e., the second column)
result = np.delete(b, 1, axis=1)

print(result)


[[1 3]
 [4 6]
 [7 9]]


In [3]:
a=[10,20,30]

b=[20,30,40]
#concatenation
print(a+b)

[10, 20, 30, 20, 30, 40]


In [4]:
A1=np.array([10,20,30])
B1=np.array([30,40,50])


print(A1+B1)

[40 60 80]


In [5]:
print(A1.ndim)

1


In [6]:
np.repeat(b,3)

array([20, 20, 20, 30, 30, 30, 40, 40, 40])

In [7]:
np.tile(b,3)

array([20, 30, 40, 20, 30, 40, 20, 30, 40])

In [8]:
C=np.arange(9)

In [9]:
C=C.reshape(3,3)

In [10]:
C

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
np.tile(C,3)

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8, 6, 7, 8]])

In [12]:
A1**2

array([100, 400, 900])

In [13]:
arr3=np.array([10,20,30,40])

In [14]:
arr3>10

array([False,  True,  True,  True])

In [15]:
np.sqrt(arr3)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532])

In [16]:
np.tan(arr3)

array([ 0.64836083,  2.23716094, -6.4053312 , -1.11721493])

In [18]:
x=np.arange(1,11)

In [19]:
x.sum()

np.int64(55)

In [20]:
x.mean()

np.float64(5.5)

In [21]:
x_mean=x.mean()

In [22]:
x-x_mean

array([-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5])

In [26]:
dev= (x-x_mean)** 2

In [29]:
dev.sum() / x.size

np.float64(8.25)

np.sqrt(dev.sum() / x.size)

In [25]:
np.sqrt((x-x_mean)** 2)

array([4.5, 3.5, 2.5, 1.5, 0.5, 0.5, 1.5, 2.5, 3.5, 4.5])

In [24]:
x.std()

np.float64(2.8722813232690143)

In [5]:
import sys
print(sys.executable)


c:\Users\admin\Desktop\ashar\.venv\Scripts\python.exe
