In [1]:
import numpy as np

In [2]:
nums = np.array([5,10,15,20,25,30,35,40,45,50])

In [3]:
nums

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [4]:
nums[1]

np.int64(10)

In [5]:
print(nums[4])

25


In [ ]:
#Accessing multiple elements using indexing in 1D Array
print(nums[[3,5,7,9]])

[20 30 40 50]


In [ ]:
#Generating a 3x3 Matrix and extracting elements using indexing
nums10 = np.arange(10,100,10).reshape(3,3)

In [14]:
print(nums10[1])

[40 50 60]


In [15]:
print(nums10[1,2])

60


In [16]:
#Insering the values index in a matrix
nums10[2,2] = 100

In [17]:
nums10

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80, 100]])

In [18]:
nums10[2]

array([ 70,  80, 100])

In [19]:
#Accesing multiple elements of diff arrays in the given 3D Array
nums10[[0,2],[2,1]]

array([30, 80])

In [20]:
#Accesing using the condition
nums10[nums10>40]

array([ 50,  60,  70,  80, 100])

In [26]:
nums10[nums10%40 == 0]

array([40, 80])

In [27]:
##Array Slicing

In [28]:
names = np.array(['Shashank','Lohit','Sai','Prateek'])

In [29]:
names.reshape(2,2)

array([['Shashank', 'Lohit'],
       ['Sai', 'Prateek']], dtype='<U8')

In [ ]:
#Slicing from second element --> prints from second element
names[1:]

array(['Lohit', 'Sai', 'Prateek'], dtype='<U8')

In [31]:
#Printing till specific index
names[: 3]

array(['Shashank', 'Lohit', 'Sai'], dtype='<U8')