In [78]:
#Matrix Operation on the Arrays
import numpy as np

In [79]:
A = np.array([[1,2,4,5]])
A

array([[1, 2, 4, 5]])

In [80]:
#Transpose of the given matrix array
B= A.transpose() #or else we can also use np.transpose(A)
B

array([[1],
       [2],
       [4],
       [5]])

In [81]:
#Dot product of two arrays
A.dot(B)

array([[46]])

In [82]:
#Another method for the same multiplication
np.dot(A,B)

array([[46]])

In [83]:
A.reshape(2,2)

array([[1, 2],
       [4, 5]])